version: '3.7'
services:
  management-restaurant:
    image: overatevntech/management-restaurant:0.0.03
    ports:
      - "8000:80"
    platform: linux/amd64
    deploy:
        mode: global
    build:
        context: .
        dockerfile: ./Dockerfile

  #Nginx Service
  nginx:
    image: nginx:1.17-alpine
    # command: sh -c "chmod 777 -Rc /var/www/html/storage && chmod 777 -Rc /var/www/html/bootstrap/cache && nginx -g \"daemon off;\""
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
