version: '3.7'
services:
  #PHP Service
  app:
    image: dashboard-tms-docker:0.0.01
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    # command: sh -c "chmod 777 -Rc /var/www/html/storage && chmod 777 -Rc /var/www/html/bootstrap/cache && nginx -g \"daemon off;\""
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
